//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabberPCL.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GabberPCL.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string common_comms_loading {
            get {
                return ResourceManager.GetString("common.comms.loading", resourceCulture);
            }
        }
        
        public static string common_comms_error {
            get {
                return ResourceManager.GetString("common.comms.error", resourceCulture);
            }
        }
        
        public static string common_comms_error_server {
            get {
                return ResourceManager.GetString("common.comms.error.server", resourceCulture);
            }
        }
        
        public static string common_comms_retry {
            get {
                return ResourceManager.GetString("common.comms.retry", resourceCulture);
            }
        }
        
        public static string common_comms_cancel {
            get {
                return ResourceManager.GetString("common.comms.cancel", resourceCulture);
            }
        }
        
        public static string common_comms_ok {
            get {
                return ResourceManager.GetString("common.comms.ok", resourceCulture);
            }
        }
        
        public static string common_menu_projects {
            get {
                return ResourceManager.GetString("common.menu.projects", resourceCulture);
            }
        }
        
        public static string common_menu_gabbers {
            get {
                return ResourceManager.GetString("common.menu.gabbers", resourceCulture);
            }
        }
        
        public static string common_menu_settings {
            get {
                return ResourceManager.GetString("common.menu.settings", resourceCulture);
            }
        }
        
        public static string settings_title {
            get {
                return ResourceManager.GetString("settings.title", resourceCulture);
            }
        }
        
        public static string settings_about {
            get {
                return ResourceManager.GetString("settings.about", resourceCulture);
            }
        }
        
        public static string settings_chooseAppLanguage {
            get {
                return ResourceManager.GetString("settings.chooseAppLanguage", resourceCulture);
            }
        }
        
        public static string settings_chooseConvoLanguage {
            get {
                return ResourceManager.GetString("settings.chooseConvoLanguage", resourceCulture);
            }
        }
        
        public static string settings_logout {
            get {
                return ResourceManager.GetString("settings.logout", resourceCulture);
            }
        }
        
        public static string settings_logout_dialog_title {
            get {
                return ResourceManager.GetString("settings.logout.dialog.title", resourceCulture);
            }
        }
        
        public static string settings_logout_dialog_message {
            get {
                return ResourceManager.GetString("settings.logout.dialog.message", resourceCulture);
            }
        }
        
        public static string settings_logout_dialog_confirm {
            get {
                return ResourceManager.GetString("settings.logout.dialog.confirm", resourceCulture);
            }
        }
        
        public static string common_ui_forms_email_label {
            get {
                return ResourceManager.GetString("common.ui.forms.email.label", resourceCulture);
            }
        }
        
        public static string common_ui_forms_password_label {
            get {
                return ResourceManager.GetString("common.ui.forms.password.label", resourceCulture);
            }
        }
        
        public static string common_ui_forms_password_confirm_label {
            get {
                return ResourceManager.GetString("common.ui.forms.password.confirm.label", resourceCulture);
            }
        }
        
        public static string common_ui_forms_email_validate_empty {
            get {
                return ResourceManager.GetString("common.ui.forms.email.validate.empty", resourceCulture);
            }
        }
        
        public static string common_ui_forms_email_validate_invalid {
            get {
                return ResourceManager.GetString("common.ui.forms.email.validate.invalid", resourceCulture);
            }
        }
        
        public static string common_ui_forms_password_validate_empty {
            get {
                return ResourceManager.GetString("common.ui.forms.password.validate.empty", resourceCulture);
            }
        }
        
        public static string common_ui_forms_password_validate_mismatch {
            get {
                return ResourceManager.GetString("common.ui.forms.password.validate.mismatch", resourceCulture);
            }
        }
        
        public static string common_ui_forms_language_error {
            get {
                return ResourceManager.GetString("common.ui.forms.language.error", resourceCulture);
            }
        }
        
        public static string common_ui_forms_language_default {
            get {
                return ResourceManager.GetString("common.ui.forms.language.default", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_zero_title {
            get {
                return ResourceManager.GetString("onboarding.ui.page.zero.title", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_zero_content {
            get {
                return ResourceManager.GetString("onboarding.ui.page.zero.content", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_first_title {
            get {
                return ResourceManager.GetString("onboarding.ui.page.first.title", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_first_content {
            get {
                return ResourceManager.GetString("onboarding.ui.page.first.content", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_second_title {
            get {
                return ResourceManager.GetString("onboarding.ui.page.second.title", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_second_content {
            get {
                return ResourceManager.GetString("onboarding.ui.page.second.content", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_third_title {
            get {
                return ResourceManager.GetString("onboarding.ui.page.third.title", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_third_content {
            get {
                return ResourceManager.GetString("onboarding.ui.page.third.content", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_fourth_title {
            get {
                return ResourceManager.GetString("onboarding.ui.page.fourth.title", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_fourth_content {
            get {
                return ResourceManager.GetString("onboarding.ui.page.fourth.content", resourceCulture);
            }
        }
        
        public static string login_api_error_GENERAL {
            get {
                return ResourceManager.GetString("login.api.error.GENERAL", resourceCulture);
            }
        }
        
        public static string login_api_error_NO_INTERNET {
            get {
                return ResourceManager.GetString("login.api.error.NO_INTERNET", resourceCulture);
            }
        }
        
        public static string login_api_error_auth_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("login.api.error.auth.INVALID_PASSWORD", resourceCulture);
            }
        }
        
        public static string login_api_error_auth_USER_404 {
            get {
                return ResourceManager.GetString("login.api.error.auth.USER_404", resourceCulture);
            }
        }
        
        public static string login_ui_title {
            get {
                return ResourceManager.GetString("login.ui.title", resourceCulture);
            }
        }
        
        public static string login_ui_submit_button {
            get {
                return ResourceManager.GetString("login.ui.submit.button", resourceCulture);
            }
        }
        
        public static string register_api_error_auth_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("register.api.error.auth.INVALID_PASSWORD", resourceCulture);
            }
        }
        
        public static string register_api_error_auth_USER_404 {
            get {
                return ResourceManager.GetString("register.api.error.auth.USER_404", resourceCulture);
            }
        }
        
        public static string register_ui_title {
            get {
                return ResourceManager.GetString("register.ui.title", resourceCulture);
            }
        }
        
        public static string register_ui_fullname_label {
            get {
                return ResourceManager.GetString("register.ui.fullname.label", resourceCulture);
            }
        }
        
        public static string register_ui_terms_label {
            get {
                return ResourceManager.GetString("register.ui.terms.label", resourceCulture);
            }
        }
        
        public static string register_ui_submit_button {
            get {
                return ResourceManager.GetString("register.ui.submit.button", resourceCulture);
            }
        }
        
        public static string register_ui_fullname_validate_empty {
            get {
                return ResourceManager.GetString("register.ui.fullname.validate.empty", resourceCulture);
            }
        }
        
        public static string register_verify_ui_page_title {
            get {
                return ResourceManager.GetString("register.verify.ui.page.title", resourceCulture);
            }
        }
        
        public static string register_verify_ui_page_content {
            get {
                return ResourceManager.GetString("register.verify.ui.page.content", resourceCulture);
            }
        }
        
        public static string register_verify_ui_page_subcontent {
            get {
                return ResourceManager.GetString("register.verify.ui.page.subcontent", resourceCulture);
            }
        }
        
        public static string register_verify_ui_button_openemail {
            get {
                return ResourceManager.GetString("register.verify.ui.button.openemail", resourceCulture);
            }
        }
        
        public static string register_verifying_activity_label {
            get {
                return ResourceManager.GetString("register.verifying.activity.label", resourceCulture);
            }
        }
        
        public static string register_verifying_ui_page_title {
            get {
                return ResourceManager.GetString("register.verifying.ui.page.title", resourceCulture);
            }
        }
        
        public static string register_verifying_ui_page_content {
            get {
                return ResourceManager.GetString("register.verifying.ui.page.content", resourceCulture);
            }
        }
        
        public static string register_verifying_ui_page_content_error {
            get {
                return ResourceManager.GetString("register.verifying.ui.page.content.error", resourceCulture);
            }
        }
        
        public static string register_verifying_ui_button_login {
            get {
                return ResourceManager.GetString("register.verifying.ui.button.login", resourceCulture);
            }
        }
        
        public static string register_verifying_api_error_auth_ALREADY_VERIFIED {
            get {
                return ResourceManager.GetString("register.verifying.api.error.auth.ALREADY_VERIFIED", resourceCulture);
            }
        }
        
        public static string register_verifying_api_error_auth_TOKEN_404 {
            get {
                return ResourceManager.GetString("register.verifying.api.error.auth.TOKEN_404", resourceCulture);
            }
        }
        
        public static string register_verifying_api_error_auth_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("register.verifying.api.error.auth.TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        public static string projects_ui_title {
            get {
                return ResourceManager.GetString("projects.ui.title", resourceCulture);
            }
        }
        
        public static string projects_ui_instructions {
            get {
                return ResourceManager.GetString("projects.ui.instructions", resourceCulture);
            }
        }
        
        public static string projects_ui_fetching {
            get {
                return ResourceManager.GetString("projects.ui.fetching", resourceCulture);
            }
        }
        
        public static string projects_ui_topics {
            get {
                return ResourceManager.GetString("projects.ui.topics", resourceCulture);
            }
        }
        
        public static string projects_ui_get_started_button {
            get {
                return ResourceManager.GetString("projects.ui.get.started.button", resourceCulture);
            }
        }
        
        public static string sessions_ui_title {
            get {
                return ResourceManager.GetString("sessions.ui.title", resourceCulture);
            }
        }
        
        public static string sessions_ui_header_instructions {
            get {
                return ResourceManager.GetString("sessions.ui.header.instructions", resourceCulture);
            }
        }
        
        public static string sessions_ui_body_instructions {
            get {
                return ResourceManager.GetString("sessions.ui.body.instructions", resourceCulture);
            }
        }
        
        public static string sessions_ui_submit_button {
            get {
                return ResourceManager.GetString("sessions.ui.submit.button", resourceCulture);
            }
        }
        
        public static string sessions_ui_message_upload_success {
            get {
                return ResourceManager.GetString("sessions.ui.message.upload.success", resourceCulture);
            }
        }
        
        public static string sessions_ui_message_upload_fail {
            get {
                return ResourceManager.GetString("sessions.ui.message.upload.fail", resourceCulture);
            }
        }
        
        public static string sessions_ui_message_upload_inprogress {
            get {
                return ResourceManager.GetString("sessions.ui.message.upload.inprogress", resourceCulture);
            }
        }
        
        public static string about_ui_title {
            get {
                return ResourceManager.GetString("about.ui.title", resourceCulture);
            }
        }
        
        public static string about_ui_content {
            get {
                return ResourceManager.GetString("about.ui.content", resourceCulture);
            }
        }
        
        public static string about_ui_url_description {
            get {
                return ResourceManager.GetString("about.ui.url.description", resourceCulture);
            }
        }
        
        public static string participants_ui_title {
            get {
                return ResourceManager.GetString("participants.ui.title", resourceCulture);
            }
        }
        
        public static string participants_ui_instructions {
            get {
                return ResourceManager.GetString("participants.ui.instructions", resourceCulture);
            }
        }
        
        public static string participants_ui_numselected {
            get {
                return ResourceManager.GetString("participants.ui.numselected", resourceCulture);
            }
        }
        
        public static string participants_ui_startrecording_button {
            get {
                return ResourceManager.GetString("participants.ui.startrecording.button", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_noneselected {
            get {
                return ResourceManager.GetString("participants.ui.validation.noneselected", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_oneselected_title {
            get {
                return ResourceManager.GetString("participants.ui.validation.oneselected.title", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_oneselected_message {
            get {
                return ResourceManager.GetString("participants.ui.validation.oneselected.message", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_oneselected_continue {
            get {
                return ResourceManager.GetString("participants.ui.validation.oneselected.continue", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_oneselected_cancel {
            get {
                return ResourceManager.GetString("participants.ui.validation.oneselected.cancel", resourceCulture);
            }
        }
        
        public static string participants_ui_dialog_add_title {
            get {
                return ResourceManager.GetString("participants.ui.dialog.add.title", resourceCulture);
            }
        }
        
        public static string participants_ui_dialog_add_positive {
            get {
                return ResourceManager.GetString("participants.ui.dialog.add.positive", resourceCulture);
            }
        }
        
        public static string participants_ui_dialog_add_negative {
            get {
                return ResourceManager.GetString("participants.ui.dialog.add.negative", resourceCulture);
            }
        }
        
        public static string consent_research_toolbar_title {
            get {
                return ResourceManager.GetString("consent.research.toolbar.title", resourceCulture);
            }
        }
        
        public static string consent_research_submit {
            get {
                return ResourceManager.GetString("consent.research.submit", resourceCulture);
            }
        }
        
        public static string consent_research_title {
            get {
                return ResourceManager.GetString("consent.research.title", resourceCulture);
            }
        }
        
        public static string consent_research_body {
            get {
                return ResourceManager.GetString("consent.research.body", resourceCulture);
            }
        }
        
        public static string consent_research_details_button {
            get {
                return ResourceManager.GetString("consent.research.details.button", resourceCulture);
            }
        }
        
        public static string consent_research_form {
            get {
                return ResourceManager.GetString("consent.research.form", resourceCulture);
            }
        }
        
        public static string consent_gabber_toolbar_title {
            get {
                return ResourceManager.GetString("consent.gabber.toolbar.title", resourceCulture);
            }
        }
        
        public static string consent_gabber_submit {
            get {
                return ResourceManager.GetString("consent.gabber.submit", resourceCulture);
            }
        }
        
        public static string consent_gabber_title_control {
            get {
                return ResourceManager.GetString("consent.gabber.title.control", resourceCulture);
            }
        }
        
        public static string consent_gabber_body_control {
            get {
                return ResourceManager.GetString("consent.gabber.body.control", resourceCulture);
            }
        }
        
        public static string consent_gabber_title_decision {
            get {
                return ResourceManager.GetString("consent.gabber.title.decision", resourceCulture);
            }
        }
        
        public static string consent_gabber_body_decision {
            get {
                return ResourceManager.GetString("consent.gabber.body.decision", resourceCulture);
            }
        }
        
        public static string consent_gabber_consent_type_public_full {
            get {
                return ResourceManager.GetString("consent.gabber.consent.type.public.full", resourceCulture);
            }
        }
        
        public static string consent_gabber_consent_type_public_brief {
            get {
                return ResourceManager.GetString("consent.gabber.consent.type.public.brief", resourceCulture);
            }
        }
        
        public static string consent_gabber_consent_type_members_full {
            get {
                return ResourceManager.GetString("consent.gabber.consent.type.members.full", resourceCulture);
            }
        }
        
        public static string consent_gabber_consent_type_members_full_plural {
            get {
                return ResourceManager.GetString("consent.gabber.consent.type.members.full.plural", resourceCulture);
            }
        }
        
        public static string consent_gabber_consent_type_members_full_singular {
            get {
                return ResourceManager.GetString("consent.gabber.consent.type.members.full.singular", resourceCulture);
            }
        }
        
        public static string consent_gabber_consent_type_members_brief {
            get {
                return ResourceManager.GetString("consent.gabber.consent.type.members.brief", resourceCulture);
            }
        }
        
        public static string consent_gabber_consent_type_private_full {
            get {
                return ResourceManager.GetString("consent.gabber.consent.type.private.full", resourceCulture);
            }
        }
        
        public static string consent_gabber_consent_type_private_full_you {
            get {
                return ResourceManager.GetString("consent.gabber.consent.type.private.full.you", resourceCulture);
            }
        }
        
        public static string consent_gabber_consent_type_private_brief {
            get {
                return ResourceManager.GetString("consent.gabber.consent.type.private.brief", resourceCulture);
            }
        }
        
        public static string conversation_consent_gabber_submit {
            get {
                return ResourceManager.GetString("conversation.consent.gabber.submit", resourceCulture);
            }
        }
        
        public static string conversation_language_prompt {
            get {
                return ResourceManager.GetString("conversation.language.prompt", resourceCulture);
            }
        }
        
        public static string consent_summary_title {
            get {
                return ResourceManager.GetString("consent.summary.title", resourceCulture);
            }
        }
        
        public static string consent_summary_subtitle {
            get {
                return ResourceManager.GetString("consent.summary.subtitle", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_content_project_title {
            get {
                return ResourceManager.GetString("consent.summary.screen.content.project.title", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_content_participants_title {
            get {
                return ResourceManager.GetString("consent.summary.screen.content.participants.title", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_content_participants_desc {
            get {
                return ResourceManager.GetString("consent.summary.screen.content.participants.desc", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_content_research_title {
            get {
                return ResourceManager.GetString("consent.summary.screen.content.research.title", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_content_research_desc {
            get {
                return ResourceManager.GetString("consent.summary.screen.content.research.desc", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_content_conversation_title {
            get {
                return ResourceManager.GetString("consent.summary.screen.content.conversation.title", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_content_conversation_desc {
            get {
                return ResourceManager.GetString("consent.summary.screen.content.conversation.desc", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_content_embargo_title {
            get {
                return ResourceManager.GetString("consent.summary.screen.content.embargo.title", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_content_embargo_desc {
            get {
                return ResourceManager.GetString("consent.summary.screen.content.embargo.desc", resourceCulture);
            }
        }
        
        public static string consent_summary_screen_action {
            get {
                return ResourceManager.GetString("consent.summary.screen.action", resourceCulture);
            }
        }
        
        public static string recording_ui_title {
            get {
                return ResourceManager.GetString("recording.ui.title", resourceCulture);
            }
        }
        
        public static string recording_ui_title_active {
            get {
                return ResourceManager.GetString("recording.ui.title.active", resourceCulture);
            }
        }
        
        public static string recording_ui_instructions_header {
            get {
                return ResourceManager.GetString("recording.ui.instructions.header", resourceCulture);
            }
        }
        
        public static string recording_ui_permission_title {
            get {
                return ResourceManager.GetString("recording.ui.permission.title", resourceCulture);
            }
        }
        
        public static string recording_ui_permission_body {
            get {
                return ResourceManager.GetString("recording.ui.permission.body", resourceCulture);
            }
        }
        
        public static string recording_ui_permission_button_negative {
            get {
                return ResourceManager.GetString("recording.ui.permission.button.negative", resourceCulture);
            }
        }
        
        public static string recording_ui_permission_button_positive {
            get {
                return ResourceManager.GetString("recording.ui.permission.button.positive", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_finish_title {
            get {
                return ResourceManager.GetString("recording.ui.dialog.finish.title", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_finish_positive {
            get {
                return ResourceManager.GetString("recording.ui.dialog.finish.positive", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_finish_negative {
            get {
                return ResourceManager.GetString("recording.ui.dialog.finish.negative", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_back_title {
            get {
                return ResourceManager.GetString("recording.ui.dialog.back.title", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_back_body {
            get {
                return ResourceManager.GetString("recording.ui.dialog.back.body", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_back_positive {
            get {
                return ResourceManager.GetString("recording.ui.dialog.back.positive", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_back_negative {
            get {
                return ResourceManager.GetString("recording.ui.dialog.back.negative", resourceCulture);
            }
        }
        
        public static string debriefing_activity_title {
            get {
                return ResourceManager.GetString("debriefing.activity.title", resourceCulture);
            }
        }
        
        public static string debriefing_congrats_title {
            get {
                return ResourceManager.GetString("debriefing.congrats.title", resourceCulture);
            }
        }
        
        public static string debriefing_congrats_body {
            get {
                return ResourceManager.GetString("debriefing.congrats.body", resourceCulture);
            }
        }
        
        public static string debriefing_consent_title {
            get {
                return ResourceManager.GetString("debriefing.consent.title", resourceCulture);
            }
        }
        
        public static string debriefing_consent_body1 {
            get {
                return ResourceManager.GetString("debriefing.consent.body1", resourceCulture);
            }
        }
        
        public static string debriefing_consent_body2 {
            get {
                return ResourceManager.GetString("debriefing.consent.body2", resourceCulture);
            }
        }
        
        public static string debriefing_consent_body3 {
            get {
                return ResourceManager.GetString("debriefing.consent.body3", resourceCulture);
            }
        }
        
        public static string debriefing_finish_button {
            get {
                return ResourceManager.GetString("debriefing.finish.button", resourceCulture);
            }
        }
    }
}
