//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabberPCL.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GabberPCL.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string common_menu_projects {
            get {
                return ResourceManager.GetString("common.menu.projects", resourceCulture);
            }
        }
        
        public static string common_menu_gabbers {
            get {
                return ResourceManager.GetString("common.menu.gabbers", resourceCulture);
            }
        }
        
        public static string common_menu_about {
            get {
                return ResourceManager.GetString("common.menu.about", resourceCulture);
            }
        }
        
        public static string common_ui_forms_email_label {
            get {
                return ResourceManager.GetString("common.ui.forms.email.label", resourceCulture);
            }
        }
        
        public static string common_ui_forms_password_label {
            get {
                return ResourceManager.GetString("common.ui.forms.password.label", resourceCulture);
            }
        }
        
        public static string common_ui_forms_email_validate_empty {
            get {
                return ResourceManager.GetString("common.ui.forms.email.validate.empty", resourceCulture);
            }
        }
        
        public static string common_ui_forms_email_validate_invalid {
            get {
                return ResourceManager.GetString("common.ui.forms.email.validate.invalid", resourceCulture);
            }
        }
        
        public static string common_ui_forms_password_validate_empty {
            get {
                return ResourceManager.GetString("common.ui.forms.password.validate.empty", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_first_title {
            get {
                return ResourceManager.GetString("onboarding.ui.page.first.title", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_first_content {
            get {
                return ResourceManager.GetString("onboarding.ui.page.first.content", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_second_title {
            get {
                return ResourceManager.GetString("onboarding.ui.page.second.title", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_second_content {
            get {
                return ResourceManager.GetString("onboarding.ui.page.second.content", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_third_title {
            get {
                return ResourceManager.GetString("onboarding.ui.page.third.title", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_third_content {
            get {
                return ResourceManager.GetString("onboarding.ui.page.third.content", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_fourth_title {
            get {
                return ResourceManager.GetString("onboarding.ui.page.fourth.title", resourceCulture);
            }
        }
        
        public static string onboarding_ui_page_fourth_content {
            get {
                return ResourceManager.GetString("onboarding.ui.page.fourth.content", resourceCulture);
            }
        }
        
        public static string login_api_error_GENERAL {
            get {
                return ResourceManager.GetString("login.api.error.GENERAL", resourceCulture);
            }
        }
        
        public static string login_api_error_NO_INTERNET {
            get {
                return ResourceManager.GetString("login.api.error.NO_INTERNET", resourceCulture);
            }
        }
        
        public static string login_api_error_AUTH_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("login.api.error.AUTH_INVALID_PASSWORD", resourceCulture);
            }
        }
        
        public static string login_api_error_AUTH_USER_404 {
            get {
                return ResourceManager.GetString("login.api.error.AUTH_USER_404", resourceCulture);
            }
        }
        
        public static string login_ui_title {
            get {
                return ResourceManager.GetString("login.ui.title", resourceCulture);
            }
        }
        
        public static string login_ui_submit_button {
            get {
                return ResourceManager.GetString("login.ui.submit.button", resourceCulture);
            }
        }
        
        public static string register_api_error_AUTH_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("register.api.error.AUTH_INVALID_PASSWORD", resourceCulture);
            }
        }
        
        public static string register_api_error_AUTH_USER_404 {
            get {
                return ResourceManager.GetString("register.api.error.AUTH_USER_404", resourceCulture);
            }
        }
        
        public static string register_ui_title {
            get {
                return ResourceManager.GetString("register.ui.title", resourceCulture);
            }
        }
        
        public static string register_ui_fullname_label {
            get {
                return ResourceManager.GetString("register.ui.fullname.label", resourceCulture);
            }
        }
        
        public static string register_ui_submit_button {
            get {
                return ResourceManager.GetString("register.ui.submit.button", resourceCulture);
            }
        }
        
        public static string register_ui_fullname_validate_empty {
            get {
                return ResourceManager.GetString("register.ui.fullname.validate.empty", resourceCulture);
            }
        }
        
        public static string register_verify_ui_page_title {
            get {
                return ResourceManager.GetString("register.verify.ui.page.title", resourceCulture);
            }
        }
        
        public static string register_verify_ui_page_content {
            get {
                return ResourceManager.GetString("register.verify.ui.page.content", resourceCulture);
            }
        }
        
        public static string register_verify_ui_button_openemail {
            get {
                return ResourceManager.GetString("register.verify.ui.button.openemail", resourceCulture);
            }
        }
        
        public static string register_verifying_activity_label {
            get {
                return ResourceManager.GetString("register.verifying.activity.label", resourceCulture);
            }
        }
        
        public static string register_verifying_ui_page_title {
            get {
                return ResourceManager.GetString("register.verifying.ui.page.title", resourceCulture);
            }
        }
        
        public static string register_verifying_ui_page_content {
            get {
                return ResourceManager.GetString("register.verifying.ui.page.content", resourceCulture);
            }
        }
        
        public static string register_verifying_ui_page_content_error {
            get {
                return ResourceManager.GetString("register.verifying.ui.page.content.error", resourceCulture);
            }
        }
        
        public static string register_verifying_ui_button_login {
            get {
                return ResourceManager.GetString("register.verifying.ui.button.login", resourceCulture);
            }
        }
        
        public static string register_verifying_api_error_ALREADY_VERIFIED {
            get {
                return ResourceManager.GetString("register.verifying.api.error.ALREADY_VERIFIED", resourceCulture);
            }
        }
        
        public static string register_verifying_api_error_AUTH_TOKEN_404 {
            get {
                return ResourceManager.GetString("register.verifying.api.error.AUTH_TOKEN_404", resourceCulture);
            }
        }
        
        public static string register_verifying_api_error_AUTH_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("register.verifying.api.error.AUTH_TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        public static string projects_ui_title {
            get {
                return ResourceManager.GetString("projects.ui.title", resourceCulture);
            }
        }
        
        public static string projects_ui_instructions {
            get {
                return ResourceManager.GetString("projects.ui.instructions", resourceCulture);
            }
        }
        
        public static string sessions_ui_title {
            get {
                return ResourceManager.GetString("sessions.ui.title", resourceCulture);
            }
        }
        
        public static string sessions_ui_header_instructions {
            get {
                return ResourceManager.GetString("sessions.ui.header.instructions", resourceCulture);
            }
        }
        
        public static string sessions_ui_body_instructions {
            get {
                return ResourceManager.GetString("sessions.ui.body.instructions", resourceCulture);
            }
        }
        
        public static string sessions_ui_submit_button {
            get {
                return ResourceManager.GetString("sessions.ui.submit.button", resourceCulture);
            }
        }
        
        public static string sessions_ui_message_upload_success {
            get {
                return ResourceManager.GetString("sessions.ui.message.upload.success", resourceCulture);
            }
        }
        
        public static string sessions_ui_message_upload_fail {
            get {
                return ResourceManager.GetString("sessions.ui.message.upload.fail", resourceCulture);
            }
        }
        
        public static string about_ui_title {
            get {
                return ResourceManager.GetString("about.ui.title", resourceCulture);
            }
        }
        
        public static string about_ui_content {
            get {
                return ResourceManager.GetString("about.ui.content", resourceCulture);
            }
        }
        
        public static string participants_ui_title {
            get {
                return ResourceManager.GetString("participants.ui.title", resourceCulture);
            }
        }
        
        public static string participants_ui_numselected {
            get {
                return ResourceManager.GetString("participants.ui.numselected", resourceCulture);
            }
        }
        
        public static string participants_ui_addparticipant_button {
            get {
                return ResourceManager.GetString("participants.ui.addparticipant.button", resourceCulture);
            }
        }
        
        public static string participants_ui_startrecording_button {
            get {
                return ResourceManager.GetString("participants.ui.startrecording.button", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_noneselected {
            get {
                return ResourceManager.GetString("participants.ui.validation.noneselected", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_oneselected_title {
            get {
                return ResourceManager.GetString("participants.ui.validation.oneselected.title", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_oneselected_message {
            get {
                return ResourceManager.GetString("participants.ui.validation.oneselected.message", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_oneselected_continue {
            get {
                return ResourceManager.GetString("participants.ui.validation.oneselected.continue", resourceCulture);
            }
        }
        
        public static string participants_ui_validation_oneselected_cancel {
            get {
                return ResourceManager.GetString("participants.ui.validation.oneselected.cancel", resourceCulture);
            }
        }
        
        public static string participants_ui_dialog_add_title {
            get {
                return ResourceManager.GetString("participants.ui.dialog.add.title", resourceCulture);
            }
        }
        
        public static string participants_ui_dialog_add_positive {
            get {
                return ResourceManager.GetString("participants.ui.dialog.add.positive", resourceCulture);
            }
        }
        
        public static string participants_ui_dialog_add_negative {
            get {
                return ResourceManager.GetString("participants.ui.dialog.add.negative", resourceCulture);
            }
        }
        
        public static string recording_ui_title {
            get {
                return ResourceManager.GetString("recording.ui.title", resourceCulture);
            }
        }
        
        public static string recording_ui_title_active {
            get {
                return ResourceManager.GetString("recording.ui.title.active", resourceCulture);
            }
        }
        
        public static string recording_ui_instructions_header {
            get {
                return ResourceManager.GetString("recording.ui.instructions.header", resourceCulture);
            }
        }
        
        public static string recording_ui_instructions_footer {
            get {
                return ResourceManager.GetString("recording.ui.instructions.footer", resourceCulture);
            }
        }
        
        public static string recording_ui_permission_title {
            get {
                return ResourceManager.GetString("recording.ui.permission.title", resourceCulture);
            }
        }
        
        public static string recording_ui_permission_body {
            get {
                return ResourceManager.GetString("recording.ui.permission.body", resourceCulture);
            }
        }
        
        public static string recording_ui_permission_button_negative {
            get {
                return ResourceManager.GetString("recording.ui.permission.button.negative", resourceCulture);
            }
        }
        
        public static string recording_ui_permission_button_positive {
            get {
                return ResourceManager.GetString("recording.ui.permission.button.positive", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_finish_title {
            get {
                return ResourceManager.GetString("recording.ui.dialog.finish.title", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_finish_positive {
            get {
                return ResourceManager.GetString("recording.ui.dialog.finish.positive", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_finish_negative {
            get {
                return ResourceManager.GetString("recording.ui.dialog.finish.negative", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_back_title {
            get {
                return ResourceManager.GetString("recording.ui.dialog.back.title", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_back_body {
            get {
                return ResourceManager.GetString("recording.ui.dialog.back.body", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_back_positive {
            get {
                return ResourceManager.GetString("recording.ui.dialog.back.positive", resourceCulture);
            }
        }
        
        public static string recording_ui_dialog_back_negative {
            get {
                return ResourceManager.GetString("recording.ui.dialog.back.negative", resourceCulture);
            }
        }
        
        public static string debriefing_ui_button_hide {
            get {
                return ResourceManager.GetString("debriefing.ui.button.hide", resourceCulture);
            }
        }
        
        public static string debriefing_ui_button_upload {
            get {
                return ResourceManager.GetString("debriefing.ui.button.upload", resourceCulture);
            }
        }
        
        public static string debriefing_ui_page_first_title {
            get {
                return ResourceManager.GetString("debriefing.ui.page.first.title", resourceCulture);
            }
        }
        
        public static string debriefing_ui_page_first_content {
            get {
                return ResourceManager.GetString("debriefing.ui.page.first.content", resourceCulture);
            }
        }
        
        public static string debriefing_ui_page_second_title {
            get {
                return ResourceManager.GetString("debriefing.ui.page.second.title", resourceCulture);
            }
        }
        
        public static string debriefing_ui_page_second_content {
            get {
                return ResourceManager.GetString("debriefing.ui.page.second.content", resourceCulture);
            }
        }
        
        public static string debriefing_ui_page_third_title {
            get {
                return ResourceManager.GetString("debriefing.ui.page.third.title", resourceCulture);
            }
        }
        
        public static string debriefing_ui_page_third_content {
            get {
                return ResourceManager.GetString("debriefing.ui.page.third.content", resourceCulture);
            }
        }
    }
}
