//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GabberPCL.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GabberPCL.Resources.StringResources", typeof(StringResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string login_api_error_GENERAL {
            get {
                return ResourceManager.GetString("login.api.error.GENERAL", resourceCulture);
            }
        }
        
        public static string login_api_error_AUTH_INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("login.api.error.AUTH_INVALID_PASSWORD", resourceCulture);
            }
        }
        
        public static string login_api_error_AUTH_USER_404 {
            get {
                return ResourceManager.GetString("login.api.error.AUTH_USER_404", resourceCulture);
            }
        }
        
        public static string login_ui_email_label {
            get {
                return ResourceManager.GetString("login.ui.email.label", resourceCulture);
            }
        }
        
        public static string login_ui_password_label {
            get {
                return ResourceManager.GetString("login.ui.password.label", resourceCulture);
            }
        }
        
        public static string login_ui_submit_button {
            get {
                return ResourceManager.GetString("login.ui.submit.button", resourceCulture);
            }
        }
        
        public static string login_ui_error_email_empty {
            get {
                return ResourceManager.GetString("login.ui.error.email.empty", resourceCulture);
            }
        }
        
        public static string login_ui_error_email_invalid {
            get {
                return ResourceManager.GetString("login.ui.error.email.invalid", resourceCulture);
            }
        }
        
        public static string login_ui_error_email_password {
            get {
                return ResourceManager.GetString("login.ui.error.email.password", resourceCulture);
            }
        }
    }
}
