// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Gabber.iOS
{
    public partial class ProjectTableViewPromptCell : UITableViewCell
    {
        public static NSString CellID = new NSString("ProjectTableViewPromptCell");

        public ProjectTableViewPromptCell(IntPtr handle) : base(handle)
        {
        }

        public void UpdateContent(string prompt)
        {
            PromptLabel.Text = prompt;
        }

    }
}
