// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using GabberPCL.Resources;
using UIKit;

namespace Gabber.iOS
{
    public partial class ProjectTableViewButtonCell : UITableViewCell
    {
        public static NSString CellID = new NSString("ProjectTableViewButtonCell");
        private int projectId;
        private Action<int> buttonCallback;

        public ProjectTableViewButtonCell(IntPtr handle) : base(handle)
        {
        }

        public void UpdateContent(int projectId, Action<int> onButtonPress)
        {
            this.projectId = projectId;
            this.buttonCallback = onButtonPress;

            GetStartedButton.SetTitle(StringResources.projects_ui_get_started_button, UIControlState.Normal);

            GetStartedButton.Layer.BorderWidth = 1.0f;
            GetStartedButton.Layer.BorderColor = UIColor.FromRGB(.43f, .80f, .79f).CGColor;

            GetStartedButton.TouchUpInside -= ButtonTouched;
            GetStartedButton.TouchUpInside += ButtonTouched;
        }

        private void ButtonTouched(object sender, EventArgs e)
        {
            buttonCallback?.Invoke(projectId);
        }
    }
}
